    LIST P = 16F887
    RADIX HEX

#include "p16f887.inc"
; CONFIG1
; __config 0x3FFA
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_OFF
; CONFIG2
; __config 0x3FFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
    org     0x00	
INICIO
    BANKSEL PR2
    MOVLW   .250
    MOVWF   PR2
    BCF	    TRISC,2;RC2 
    BANKSEL CCPR1L
    MOVLW   B'00000000' ;80% MSB
    MOVWF   CCPR1L
    MOVLW   B'00001111'
    MOVWF   CCP1CON
    BSF	    T2CON,1 ;16 PRESCALER
    BSF	    T2CON,2; TMR2 ON
    BANKSEL PORTA
PWM
    movf    PORTD, W
    movwf   CCPR1L
    goto    PWM
	END



